"use client";

import { useState } from "react";
import { Check, KeyRound, Settings2, SlidersHorizontal } from "lucide-react";

export default function SettingsPage() {
  const [streaming, setStreaming] = useState(true); const [saving, setSaving] = useState(true); const [saved, setSaved] = useState(false);
  const toggle = (value: boolean, update: (next: boolean) => void, label: string) => <button onClick={() => update(!value)} className="flex w-full items-center justify-between py-4 text-left"><div><p className="text-xs font-medium text-zinc-200">{label}</p><p className="mt-1 text-[11px] text-zinc-500">{value ? "Enabled for this workspace" : "Disabled for this workspace"}</p></div><span className={`relative h-5 w-9 rounded-full transition ${value ? "bg-[#a78b71]" : "bg-zinc-800"}`}><span className={`absolute top-1 h-3 w-3 rounded-full bg-white transition ${value ? "left-5" : "left-1"}`} /></span></button>;
  return <div className="h-full overflow-y-auto bg-[#09090b] p-6 text-zinc-100"><div className="mb-6 border-b border-zinc-800 pb-5"><p className="workspace-label">Workspace controls</p><h1 className="mt-2 text-lg font-semibold">Settings</h1><p className="mt-1 text-xs text-zinc-500">Configure how Capsule AI operates across this workspace.</p></div><div className="grid max-w-4xl gap-5 lg:grid-cols-[1fr_280px]"><div className="space-y-5"><section className="workspace-card"><div className="flex items-center gap-2 border-b border-zinc-800 px-4 py-3"><SlidersHorizontal size={15} className="text-[#c9b8a0]" /><h2 className="text-xs font-semibold">Workflow behavior</h2></div><div className="divide-y divide-zinc-800 px-4">{toggle(streaming, setStreaming, "Stream model responses")}{toggle(saving, setSaving, "Save conversations to Capsule memory")}</div></section><section className="workspace-card p-4"><div className="flex items-center gap-2"><Settings2 size={15} className="text-[#c9b8a0]" /><div><h2 className="text-xs font-semibold">Default model</h2><p className="mt-1 text-[11px] text-zinc-500">Used when a workflow has no model override.</p></div></div><select className="mt-4 h-9 w-full rounded-md border border-zinc-800 bg-[#0a0a0a] px-3 text-xs text-zinc-300 outline-none"><option>GPT-4o</option><option>Claude 3.5 Sonnet</option><option>Gemini 2.0 Flash</option><option>Llama 3.2 Local</option></select></section><button onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 2500); }} className="inline-flex h-9 items-center gap-2 rounded-md bg-[#a78b71] px-4 text-xs font-semibold text-black hover:bg-[#e8d5b7]">{saved ? <Check size={14} /> : null}{saved ? "Settings saved" : "Save changes"}</button></div><aside className="workspace-card h-fit p-4"><div className="flex items-center gap-2"><KeyRound size={15} className="text-[#c9b8a0]" /><h2 className="text-xs font-semibold">Connected gateway</h2></div><div className="mt-5 space-y-3 text-[11px]"><div className="flex justify-between text-zinc-500"><span>API status</span><span className="text-emerald-400">Operational</span></div><div className="flex justify-between text-zinc-500"><span>Endpoint</span><span className="font-mono text-zinc-300">localhost:3001</span></div><div className="flex justify-between text-zinc-500"><span>Memory store</span><span className="text-zinc-300">PostgreSQL + Qdrant</span></div></div></aside></div></div>;
}
