"use client";

import { useMemo, useState } from "react";
import { CheckCircle2, Database, Folder, Plus, Search, User, Zap } from "lucide-react";

type Capsule = { id: string; name: string; type: "PROJECT" | "TASK" | "USER" | "CONVERSATION"; updatedAt: string; size: string; active: boolean };
const initialCapsules: Capsule[] = [
  { id: "1", name: "Capsule Platform", type: "PROJECT", updatedAt: "2 mins ago", size: "1.2 MB", active: true },
  { id: "2", name: "Frontend Refactoring", type: "TASK", updatedAt: "1 hour ago", size: "342 KB", active: true },
  { id: "3", name: "GSGMK Preferences", type: "USER", updatedAt: "1 day ago", size: "12 KB", active: true },
  { id: "4", name: "Mechanical CAD Export", type: "PROJECT", updatedAt: "3 days ago", size: "4.5 MB", active: false },
  { id: "5", name: "Architecture Review", type: "CONVERSATION", updatedAt: "1 week ago", size: "89 KB", active: false },
];

export default function CapsulesPage() {
  const [capsules, setCapsules] = useState(initialCapsules); const [query, setQuery] = useState(""); const [type, setType] = useState("ALL"); const [notice, setNotice] = useState("");
  const filtered = useMemo(() => capsules.filter((capsule) => (type === "ALL" || capsule.type === type) && capsule.name.toLowerCase().includes(query.toLowerCase())), [capsules, query, type]);
  const createCapsule = () => { const number = capsules.length + 1; setCapsules((current) => [{ id: String(Date.now()), name: `Untitled Capsule ${number}`, type: "PROJECT", updatedAt: "just now", size: "0 KB", active: true }, ...current]); setNotice("New Capsule created. Select it to add context."); };
  return <div className="h-full overflow-y-auto bg-[#09090b] p-6 text-zinc-100"><div className="mb-6 flex flex-col gap-4 border-b border-zinc-800 pb-5 md:flex-row md:items-end md:justify-between"><div><p className="workspace-label">Memory registry</p><h1 className="mt-2 text-lg font-semibold">Capsules</h1><p className="mt-1 text-xs text-zinc-500">Structured project memory available to your workflows.</p></div><button onClick={createCapsule} className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-indigo-500 px-3 text-xs font-semibold text-white hover:bg-indigo-400"><Plus size={15} /> Create capsule</button></div>{notice && <div className="mb-4 flex items-center gap-2 rounded-md border border-[#a78b71]/30 bg-[#a78b71]/10 px-3 py-2 text-xs text-[#e8d5b7]"><CheckCircle2 size={14} /> {notice}</div>}<div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="flex h-9 max-w-md flex-1 items-center gap-2 rounded-md border border-zinc-800 bg-[#0c0c0e] px-3"><Search size={15} className="text-zinc-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-xs outline-none placeholder:text-zinc-600" placeholder="Search capsules..." /></label><select value={type} onChange={(event) => setType(event.target.value)} className="h-9 rounded-md border border-zinc-800 bg-[#0c0c0e] px-3 text-xs text-zinc-300 outline-none"><option value="ALL">All types</option><option value="PROJECT">Project</option><option value="TASK">Task</option><option value="USER">User</option><option value="CONVERSATION">Conversation</option></select></div><p className="mb-3 text-[11px] text-zinc-500">{filtered.length} of {capsules.length} capsules</p><div className="grid gap-3 pb-8 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((capsule) => { const Icon = capsule.type === "PROJECT" ? Folder : capsule.type === "USER" ? User : capsule.type === "TASK" ? CheckCircle2 : Database; return <button onClick={() => setNotice(`${capsule.name} is now the active context.`)} key={capsule.id} className="workspace-card group min-h-44 p-4 text-left hover:border-[#a78b71]/50 hover:bg-white/[.06]"><div className="flex items-start justify-between"><div className="grid h-9 w-9 place-items-center rounded-md bg-white/[.06] text-[#c9b8a0]"><Icon size={18} /></div>{capsule.active && <span className="flex items-center gap-1 text-[10px] text-emerald-400"><Zap size={11} /> Active</span>}</div><h2 className="mt-6 text-sm font-semibold group-hover:text-[#e8d5b7]">{capsule.name}</h2><p className="mt-1 text-[11px] uppercase tracking-wider text-zinc-500">{capsule.type} capsule</p><div className="mt-5 flex justify-between border-t border-zinc-800 pt-3 text-[11px] text-zinc-500"><span>{capsule.updatedAt}</span><span>{capsule.size}</span></div></button>; })}</div>{filtered.length === 0 && <div className="workspace-card grid h-40 place-items-center text-sm text-zinc-500">No capsules match your current search.</div>}</div>;
}
